---
- apt_repository:
    repo: deb http://us.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse
    state: present

- apt_repository:
    repo: deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse
    state: present

- apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
    state: present

- name: apt update if not done recently
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: apt install dependencies
  apt:
    name:
      - bcftools
      - beagle
      - plink1.9
      - python
      - python-pip
      - r-base
      - r-base-dev
      - samtools
      - tabix
      - vcftools

- name: pip install dependencies
  pip:
    executable: /usr/bin/pip2
    name:
      - pysam

- include: admixture.yml
  vars:
    slug: admixture_linux-1.3.0
    workspace: "/tmp"

- include: haskell.yml
