---
- include: apt.yml

- name: apt install complete dependencies
  apt:
    name:
      - apt-utils
      - autoconf
      - automake
      - awscli
      - build-essential
      - cmake
      - curl
      - dkms
      - gawk
      - git-core
      - htop
      - jq
      - kmod
      - less
      - libboost-all-dev
      - libc++-dev
      - libevent-dev
      - libncurses5-dev
      - libreadline-dev
      - libtool
      - libutempter-dev
      - man-db
      - manpages
      - module-init-tools
      - mosh
      - p7zip
      - p7zip-full
      - p7zip-rar
      - pkg-config
      - python
      - python-pip
      - python3
      - python3-pip
      - rar
      - rlwrap
      - s3fs
      - screen
      - silversearcher-ag
      - sqlite3
      - sudo
      - tmux
      - unrar
      - uuid-runtime
      - vim
      - zsh
