---
- apt_repository:
    repo: deb http://us.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse
    state: present

- apt_repository:
    repo: deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse
    state: present

- apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
    state: present

- name: apt update if not done recently
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: apt install dependencies
  apt:
    name:
      - kmod
