---
- include: apt.yml

- name: apt install dependencies
  apt:
    name:
      - bcftools
      - beagle
      - plink1.9
      - python
      - python-pip
      - r-base
      - r-base-dev
      - samtools
      - tabix
      - vcftools

- name: pip install dependencies
  pip:
    executable: /usr/bin/pip2
    name:
      - pysam

- include: admixture.yml
  vars:
    slug: admixture_linux-1.3.0
    workspace: "/tmp"

- include: haskell.yml
