---
- name: enable Amazon Linux Extras
  command: "amazon-linux-extras enable {{item.name}}"
  with_items:
    - epel
    - lustre2.10

- name: upgrade all packages
  yum:
    name: "*"
    state: latest

- name: install new packages
  yum:
    name:
      - autoconf
      - automake
      - cmake3
      - ec2-instance-connect
      - epel-release
      - gcc
      - gcc-c++
      - git
      - libevent
      - libevent-devel
      - libtool
      - lustre-client
      - ncurses
      - ncurses-devel
      - openssl
      - openssl-devel
      - protobuf
      - protobuf-devel
      - python2-pip
      - python3
      - python3-pip
      - rlwrap
      - screen
      - zlib-devel
    state: present

- include: tmux.yml
  vars:
    url: "https://github.com/tmux/tmux/releases/download/2.9a/tmux-2.9a.tar.gz"
    archive: "{{ workspace }}/tmux-2.9a.tar.gz"
    location:  "{{ workspace }}/tmux-2.9a"

- include: mosh.yml
  vars:
    url: "https://mosh.org/mosh-1.3.2.tar.gz"
    archive: "{{ workspace }}/mosh-1.3.2.tar.gz"
    location:  "{{ workspace }}/mosh-1.3.2"
