---
- name: Enable non-root FUSE mounts
  lineinfile:
    path: /etc/fuse.conf
    regexp: "#user_allow_other"
    state: present
    line: "user_allow_other"

- name: Add yas3fs shutdown script
  copy:
    src: "files/unmount-yas3fs.init.d"
    dest: "/root/unmount-yas3fs"
    mode: u+x,g+x,o+x

- name: Add yas3fs shutdown systemd service
  copy:
    src: "files/unmount-yas3fs.service"
    dest: "/etc/systemd/system/unmount-yas3fs.service"

- name: Enable yas3fs unmount service
  command: "systemctl enable unmount-yas3fs"
