version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
          
      - run: |
          docker ps -a
          docker build -t circleci:run_tests .
          docker images
          docker run -it circleci:run_tests /bin/bash
          mamba convert_ancestry/test_convert_ancestry.py
