version: 2
jobs:
  build:
    machine: true

    steps:

      - checkout
          
      - run: |
          docker build -t circleci:run_tests .
          docker run -i circleci:run_tests
          python setup.py install
          mamba convert_ancestry/test_convert_ancestry.py
          
