version: 2
jobs:
  build:
    machine: true
      image: circleci/classic:latest

    steps:
      - checkout
      - setup_remote_docker:
          
      - run: |
          ls
          docker ps -a
          docker build -t circleci:run_tests .
          echo BUILT YO
          docker ps -a
          ls
          docker start circleci:run_tests
          mamba convert_ancestry/test_convert_ancestry.py
