version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run: |
          docker build -t circleci:run_tests .
          echo BUILT YO
          docker run -it circleci:run_tests /bin/bash
          mamba convert_ancestry/test_convert_ancestry.py
