version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y docker
          docker build -t circleci:run_tests .
          echo BUILT YO
          docker run -it circleci:run_tests /bin/bash
          mamba convert_ancestry/test_convert_ancestry.py
