---
- hosts: all

  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - include: ../software/pkgs-minimal.yml
    - include: ../software/ssh.yml
    - include: ../software/goofys.yml

    - copy:
        src: '../files/bootstrap'
        dest: '/root/bootstrap'
        mode: '744'
