---
- hosts: all

  become: yes
  become_user: root
  become_method: sudo

  tasks:

    - include: ../software/pkgs-complete.yml
    - include: ../software/ec2.yml
    - include: ../software/ssh.yml
    - include: ../software/yas3fs/playbook.yml
    # - include: ../software/goofys.yml
