---
- name: provision base system
  hosts: all

  gather_facts: no

  tasks:
    - name: bootstrap python
      raw: test -e /usr/bin/python3 || (apt-get -y update && apt-get install -y python3-minimal)

    - name: bootstrap sudo
      raw: test -e /usr/bin/sudo || (apt-get install -y sudo)

    - name: bootstrap curl
      raw: test -e /usr/bin/curl || (apt-get install -y curl)
